from pydantic import BaseModel, Field, ConfigDict


# ============================================================
# Ask Request
# ============================================================

class AskRequest(BaseModel):
    """
    Request body for the RAG question-answering endpoint.
    """

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "question": "What is the primary focus of Google LLC?"
            }
        }
    )

    question: str = Field(
        ...,
        min_length=1,
        max_length=1000,
        description="The question to ask the RAG system."
    )


# ============================================================
# Ask Response
# ============================================================

class AskResponse(BaseModel):
    """
    Response returned by the RAG API.
    """

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "question": "What is the primary focus of Google LLC?",
                "answer": "Google's primary focus is on internet-related services and products.",
                "latency_ms": 4521.37
            }
        }
    )

    question: str = Field(
        ...,
        description="The original question."
    )
    answer: str = Field(
        ...,
        description="Answer generated by the RAG system."
    )

    latency_ms: float = Field(
        ...,
        description="Total time taken by the RAG system to process the request, in milliseconds."
    )

# ============================================================
# Health Response
# ============================================================

class HealthResponse(BaseModel):
    """
    Health status of the RAG API.
    """

    status: str = Field(
        description="Current API health status."
    )